steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_API_URL=https://rugbylive-api-781497782595.europe-west2.run.app
      - -t
      - europe-west2-docker.pkg.dev/rugby-live-9c1c7/rugbylive-api/rugbylive-web:latest
      - .
images:
  - europe-west2-docker.pkg.dev/rugby-live-9c1c7/rugbylive-api/rugbylive-web:latest
